Repository apache/james-project, pull requests merged in 2021-04, with the labels that each got.

#345 JAMES-1489 Failing test for UTF-8 IMAP search
  server/protocols/protocols-imap4/src/test/java/org/apache/james/imapserver/netty/IMAPServerTest.java
Labels: waiting merge

#346 JAMES-3529 Validate version when set Filter
  server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/FilteringManagement.java
  server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/Version.java
  server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/DefineRulesCommand.java
  server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/DefineRulesCommandHandler.java
  server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/EventSourcingFilteringManagement.java
  server/data/data-jmap/src/main/java/org/apache/james/jmap/api/filtering/impl/FilteringAggregate.java
  server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/FilteringManagementContract.java
  server/data/data-jmap/src/test/java/org/apache/james/jmap/api/filtering/impl/DefineRulesCommandTest.java
  server/protocols/jmap-draft/src/main/java/org/apache/james/jmap/draft/methods/SetFilterMethod.java
  server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/mailet/filter/JMAPFilteringExtension.java
  server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/mailet/filter/JMAPFilteringTest.java
Labels: waiting merge

#361 JAMES-2884 Email/query s/comparator/sort/
  server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/BackReferenceContract.scala
  server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailQueryMethodContract.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailQuery.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailQueryMethod.scala
Labels: waiting merge

#375 JAMES-3255 Tag some failing LinShare tests as unstable
  third-party/linshare/src/test/java/org/apache/james/linshare/LinshareBlobExportMechanismTest.java
  third-party/linshare/src/test/java/org/apache/james/linshare/LinshareTest.java
  third-party/linshare/src/test/java/org/apache/james/linshare/client/LinshareAPITest.java
Labels: waiting merge

#365 JAMES-3520 MDN/parse should position forEmailId property
  server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/resources/eml/mdn_relate_original_message.eml
  server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/MDNParseMethodContract.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/MDNParseSerializer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/MDNParse.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MDNParseMethod.scala
Labels: waiting merge

#387 [DOCUMENTATION] Detail convenience downloads upon releases
  docs/modules/community/pages/release.adoc
Labels: waiting merge

#388 [FIX] update openjpa version in startup.sh for demo image
  dockerfiles/run/guice/provisioned/startup.sh
Labels: waiting merge

#394 JAMES-3566 Skip EmailSubmission/set implicit Email/set call when no onSuccessXXX properties
  server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSubmissionSetMethodContract.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSubmissionSet.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala
Labels: bug

#395 JAMES-3525 verifyIdentity should not fail on null sender
  protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/AbstractSenderAuthIdentifyVerificationRcptHook.java
  server/mailet/integration-testing/src/test/java/org/apache/james/smtp/SmtpIdentityVerificationTest.java
  server/testing/src/main/java/org/apache/james/utils/SMTPMessageSender.java
Labels: bug, waiting merge

#405 JAMES-3569 Prevent loss of mail attributes in RRT mailet
  server/mailet/mailets/src/main/java/org/apache/james/transport/mailets/RecipientRewriteTableProcessor.java
  server/mailet/mailets/src/test/java/org/apache/james/transport/mailets/RecipientRewriteTableProcessorTest.java
Labels: waiting merge
