Repository apache/james-project, pull requests merged in 2023-06, with the labels that each got.

#1593 JAMES-3911 JPA: optimize applicable flags with a native query
  mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/JPAMessageMapper.java
Labels: enhancement, backport-3.8.x

#1594 FIX Proxy for SMTPS
  protocols/netty/src/main/java/org/apache/james/protocols/netty/AbstractSSLAwareChannelPipelineFactory.java
Labels: bug, backport-3.8.x

#1598 [FIX] Domain env variable should not fail when domain exists
  server/data/data-library/src/main/java/org/apache/james/domainlist/lib/AbstractDomainList.java
  server/data/data-library/src/test/java/org/apache/james/domainlist/lib/AbstractDomainListPrivateMethodsTest.java
Labels: bug, enhancement, need-backort-3.8.x

#1561 JAMES 3822 - FutureRelease for JMAP
  server/container/guice/protocols/jmap/src/main/java/org/apache/james/jmap/draft/JMAPModule.java
  server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSubmissionSetMethodFutureReleaseContract.scala
  server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/SessionRoutesContract.scala
  server/protocols/jmap-rfc-8621-integration-tests/memory-jmap-rfc-8621-integration-tests/src/test/java/org/apache/james/jmap/rfc8621/memory/MemoryEmailSubmissionSetMethodFutureReleaseTest.java
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Capabilities.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/Capability.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/JmapRfc8621Configuration.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/json/EmailSubmissionSetSerializer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailSubmissionSet.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala
  server/protocols/jmap-rfc-8621/src/test/scala/org/apache/james/jmap/json/EmailSubmissionSetSerializerTest.scala
  server/queue/queue-api/src/main/java/org/apache/james/queue/api/MailQueue.java
  server/queue/queue-memory/src/main/java/org/apache/james/queue/memory/MemoryMailQueueFactory.java
  server/queue/queue-pulsar/src/main/scala/org/apache/james/queue/pulsar/PulsarMailQueue.scala
Labels: new_feature

#1608 JAMES-3918 Force deletion of user mailboxes
  server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc
  server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/routes/UserMailboxesRoutes.java
  server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/UserMailboxesService.java
  server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
  src/site/markdown/server/manage-webadmin.md
Labels: enhancement, need-backort-3.8.x

#1599 [SITE] Guest post for fail2ban setup
  src/homepage/_posts/2023-06-20-fail2ban.markdown
Labels: documentation

#1610 JAMES-3680 Warn when plain is not allowed
  protocols/imap/src/main/java/org/apache/james/imap/processor/AuthenticateProcessor.java
  protocols/imap/src/main/java/org/apache/james/imap/processor/LoginProcessor.java
Labels: enhancement, need-backort-3.8.x

#1601 Add simple null-check in JPAMailboxMessage #JAMES-3915
  mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/model/openjpa/JPAMailboxMessage.java
  mailbox/jpa/src/test/java/org/apache/james/mailbox/jpa/mail/model/openjpa/JPAMailboxMessageTest.java
Labels: bug, backport-3.8.x

#1614 JAMES-3680 Warn when plain is not allowed (#1610) [3.8.x]
  protocols/imap/src/main/java/org/apache/james/imap/processor/AuthenticateProcessor.java
  protocols/imap/src/main/java/org/apache/james/imap/processor/LoginProcessor.java
Labels: backport-3.8.x

#1609 JAMES-3919 RabbitMQMailQueue: clean up cassandra projection when we c…
  backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQManagementAPI.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Enqueuer.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueue.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/api/FakeMailQueueView.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/api/MailQueueView.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueView.java
  server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java
Labels: bug, enhancement, need-backort-3.8.x

#1611 JAMES-3918 Force deletion of user mailboxes (#1608) [3.8.x]
  server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc
  server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/routes/UserMailboxesRoutes.java
  server/protocols/webadmin/webadmin-mailbox/src/main/java/org/apache/james/webadmin/service/UserMailboxesService.java
  server/protocols/webadmin/webadmin-mailbox/src/test/java/org/apache/james/webadmin/routes/UserMailboxesRoutesTest.java
  src/site/markdown/server/manage-webadmin.md
Labels: backport-3.8.x

#1615 JAMES-3919 RabbitMQMailQueue: clean up cassandra projection when we c…
  backends-common/rabbitmq/src/main/java/org/apache/james/backends/rabbitmq/RabbitMQManagementAPI.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Dequeuer.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/Enqueuer.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueue.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/api/FakeMailQueueView.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/api/MailQueueView.java
  server/queue/queue-rabbitmq/src/main/java/org/apache/james/queue/rabbitmq/view/cassandra/CassandraMailQueueView.java
  server/queue/queue-rabbitmq/src/test/java/org/apache/james/queue/rabbitmq/RabbitMQMailQueueTest.java
Labels: backport-3.8.x
