Repository apache/james-project, pull requests merged in 2023-04, with the labels that each got.

#1512 JAMES-3775 DockerClamAV - update waiting strategy
  third-party/clamav/src/test/java/org/apache/james/clamav/DockerClamAV.java
Labels: build

#1513 [CHANGELOG] Refresher as of 07/04/2023
  CHANGELOG.md
Labels: documentation

#1521 Revert "[ENHANCEMENT] NettyStreamImapRequestLineReader: Buffer comman…
  server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyStreamImapRequestLineReader.java
Labels: bug

#1520 JAMES-3292 More filters for listing webadmin tasks
  server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc
  server/protocols/webadmin/webadmin-core/src/main/java/org/apache/james/webadmin/routes/TasksRoutes.java
  server/protocols/webadmin/webadmin-core/src/test/java/org/apache/james/webadmin/routes/TasksRoutesTest.java
  src/site/markdown/server/manage-webadmin.md
Labels: enhancement

#1535 [REFACTORING] ReactorOpenSearchClient: Use Mono::fromFuture
  backends-common/opensearch/src/main/java/org/apache/james/backends/opensearch/ReactorOpenSearchClient.java
Labels: enhancement

#1536 JAMES-3904 Support LDAPS
  server/apps/distributed-app/docs/modules/ROOT/pages/configure/usersrepository.adoc
  server/data/data-ldap/src/main/java/org/apache/james/user/ldap/LdapRepositoryConfiguration.java
  server/data/data-ldap/src/main/java/org/apache/james/user/ldap/ReadOnlyLDAPUsersDAO.java
  server/data/data-ldap/src/test/java/org/apache/james/user/ldap/LdapGenericContainer.java
  server/data/data-ldap/src/test/java/org/apache/james/user/ldap/ReadOnlyUsersLDAPRepositoryTest.java
  src/site/xdoc/server/config-users.xml
Labels: enhancement

#1537 JAMES-2791 Avoid incoherent mail repository count
  server/container/guice/mailrepository-cassandra/src/main/java/org/apache/james/modules/mailrepository/CassandraMailRepositoryModule.java
  server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepository.java
  server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryCountDAO.java
  server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryFactory.java
  server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryKeysDAO.java
  server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryModule.java
  server/mailrepository/mailrepository-cassandra/src/main/java/org/apache/james/mailrepository/cassandra/MailRepositoryTable.java
  server/mailrepository/mailrepository-cassandra/src/test/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryCountDAOTest.java
  server/mailrepository/mailrepository-cassandra/src/test/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryTest.java
  server/mailrepository/mailrepository-cassandra/src/test/java/org/apache/james/mailrepository/cassandra/CassandraMailRepositoryWithFakeImplementationsTest.java
Labels: enhancement

#1539 [FIX] Improve DistributedTaskManagerTest stability
  server/task/task-distributed/src/test/java/org/apache/james/task/eventsourcing/distributed/DistributedTaskManagerTest.java
  server/task/task-memory/src/main/scala/org/apache/james/task/eventsourcing/DecisionProjection.scala
Labels: enhancement, build

#1541 [DOCUMENTATION] Recommend the use of PROXY protocol
  server/apps/distributed-app/docs/modules/ROOT/pages/operate/security.adoc
Labels: documentation, security

#1542 [DOCUMENTATION] JMAP Email Query View task documentation was missing
  server/apps/distributed-app/docs/modules/ROOT/pages/operate/webadmin.adoc
  src/site/markdown/server/manage-webadmin.md
Labels: documentation
