Repository apache/james-project, pull requests merged in 2024-02, with the labels that each got.

#1950 JAMES-2086 Improve COPY error message when OverQuota
  mpt/impl/imap-mailbox/core/src/main/resources/org/apache/james/imap/scripts/Quota.test
  protocols/imap/src/main/java/org/apache/james/imap/processor/AbstractMessageRangeProcessor.java
  protocols/imap/src/main/java/org/apache/james/imap/processor/AppendProcessor.java
Labels: enhancement

#1976 [ENHANCEMENT] Add SSL information into SMTP header
  protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/ReceivedDataLineFilter.java
  server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPSTest.java
  server/protocols/protocols-smtp/src/test/resources/smtpserver-tls.xml
Labels: enhancement

#1980 [FIX] MailReceptionCheck should not call sink concurrently
  server/container/feature-checks/src/main/java/org/apache/james/healthcheck/MailReceptionCheck.java
Labels: bug

#1979 [FIX] Apply RFC-5321 syntax validation for EHLO
  protocols/netty/src/main/java/org/apache/james/protocols/netty/NettyServer.java
  protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/HeloCmdHandler.java
  protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/EhloCmdHandler.java
  server/apps/memory-app/src/test/java/org/apache/james/LmtpIntegrationTest.java
  server/protocols/protocols-lmtp/src/test/java/org/apache/james/lmtpserver/LmtpServerTest.java
  server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPProxyProtocolTest.java
  server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPServerTest.java
  server/protocols/protocols-smtp/src/test/java/org/apache/james/smtpserver/SMTPTestConfiguration.java
Labels: bug

#1991 JAMES-3986 AttachmentFileNameIs should be decently tested
  mailet/standard/src/main/java/org/apache/james/transport/matchers/AttachmentFileNameIs.java
  mailet/standard/src/test/java/org/apache/james/transport/matchers/AttachmentFileNameIsTest.java
  mailet/standard/src/test/resources/nested.zip
  mailet/standard/src/test/resources/sonde.zip
Labels: bug

#1998 [FIX] Lower log level of SSL handshake exceptions
  protocols/netty/src/main/java/org/apache/james/protocols/netty/BasicChannelInboundHandler.java
  server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapChannelUpstreamHandler.java
Labels: enhancement

#1995 [FIX] Email/set should allow creating an email with attachment of a d…
  server/protocols/jmap-rfc-8621-integration-tests/jmap-rfc-8621-integration-tests-common/src/main/scala/org/apache/james/jmap/rfc8621/contract/EmailSetMethodContract.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetMethod.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetMethod.scala
Labels: bug

#2012 [FIX] LOG JMAP errors
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/Method.scala
Labels: enhancement

#2013 [FIX] IMAP LEAK: CLOSE, UNSELECT
  server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyImapSession.java
Labels: bug

#2019 File buffering for message storer
  mailbox/jpa/src/main/java/org/apache/james/mailbox/jpa/mail/JPAAttachmentMapper.java
  mailbox/memory/src/main/java/org/apache/james/mailbox/inmemory/mail/InMemoryAttachmentMapper.java
  mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/FileBufferedBodyFactory.java
  mailbox/store/src/main/java/org/apache/james/mailbox/store/mail/model/impl/MessageParser.java
Labels: enhancement

#2039 [FIX] Mime parsing on parallel scheduler
  mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageIdManager.java
  mailbox/store/src/main/java/org/apache/james/mailbox/store/StoreMessageManager.java
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailBodyPart.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/mail/EmailImport.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailImportMethod.scala
Labels: enhancement

#2037 More jmap logs
  protocols/smtp/src/main/java/org/apache/james/protocols/smtp/core/esmtp/AuthCmdHandler.java
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/core/ProblemDetails.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegateSetCreatePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegateSetDeletePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/DelegatedAccountDeletePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailImportMethod.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetCreatePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetDeletePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSetUpdatePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/EmailSubmissionSetMethod.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetCreatePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetDeletePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/IdentitySetUpdatePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetCreatePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetDeletePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MailboxSetUpdatePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionSetCreatePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionSetDeletePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/PushSubscriptionUpdatePerformer.scala
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/VacationResponseSetMethod.scala
Labels: enhancement

#1904 [SITE] Mime4J 0.8.10 release
  src/homepage/_posts/2024-01-08-mime4j-0.8.10.markdown
Labels: documentation

#2038 [FIX] MailReceptionCheck do not send the mail before we actively list…
  server/container/feature-checks/src/main/java/org/apache/james/healthcheck/MailReceptionCheck.java
Labels: bug

#2045 [CHANGELOG] Mention 3.7.5 and 3.8.1 releases
  CHANGELOG.md
Labels: documentation

#2046 Document new CVEs
  server/apps/distributed-app/docs/modules/ROOT/pages/operate/security.adoc
  src/site/xdoc/server/feature-security.xml
Labels: documentation

#2043 JAMES-4009 StripAttachment should explicitly handle duplicates
  mailet/standard/src/main/java/org/apache/james/transport/mailets/StripAttachment.java
  mailet/standard/src/test/java/org/apache/james/transport/mailets/StripAttachmentTest.java
Labels: enhancement

#2021 JAMES-4002 AES blob store tuning to reduce memory pressure
  server/apps/distributed-app/docs/modules/ROOT/pages/configure/blobstore.adoc
  server/apps/distributed-app/sample-configuration/jvm.properties
  server/blob/blob-aes/pom.xml
  server/blob/blob-aes/src/main/java/org/apache/james/blob/aes/AESBlobStoreDAO.java
  server/blob/blob-api/src/main/java/org/apache/james/blob/api/BlobStoreDAO.java
  server/blob/blob-s3/src/main/java/org/apache/james/blob/objectstorage/aws/S3BlobStoreDAO.java
Labels: enhancement

#2058 [UPGRADE] MIME4J 0.8.9 -> 0.8.10
  mailbox/store/src/test/resources/eml/james-3901.json
  pom.xml
  server/protocols/jmap-draft/src/test/java/org/apache/james/jmap/draft/methods/MIMEMessageConverterTest.java
Labels: enhancement

#2062 JAMES-4013 Relay MDN/send
  server/protocols/jmap-rfc-8621/src/main/scala/org/apache/james/jmap/method/MDNSendMethod.scala
Labels: bug

#2064 [BUILD] RemoteDeliveryErrorHandlingTest was unstable
  server/mailet/remote-delivery-integration-testing/src/test/java/org/apache/james/mailets/RemoteDeliveryErrorHandlingTest.java
Labels: build

#2061 [FIX] java.util.NoSuchElementException: requestDecoder
  server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapRequestFrameDecoder.java
Labels: enhancement

#2057 JAMES-4012 Lenient MDN parsing for human readable part
  mdn/src/main/java/org/apache/james/mdn/MDN.java
  mdn/src/test/java/org/apache/james/mdn/MDNTest.java
Labels: enhancement

#2051 JAMES-1717 Notification Registry - handle case Ints.checkedCast throws out of range when expireDate too far
  server/data/data-cassandra/src/main/java/org/apache/james/vacation/cassandra/CassandraNotificationRegistry.java
  server/data/data-cassandra/src/test/java/org/apache/james/vacation/cassandra/CassandraNotificationRegistryTest.java
Labels: bug

#2052 JAMES-4007 Getting a second shot at IMAP large litteral management
  server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/ImapRequestFrameDecoder.java
  server/protocols/protocols-imap4/src/main/java/org/apache/james/imapserver/netty/NettyStreamImapRequestLineReader.java
Labels: bug
